image: docker:24.0.5

services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

stages:
  - build
  - release

build_images:
  stage: build
  script:
    - apk add --no-cache bash zip
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker build --platform linux/arm64 pipa-endeavouros-builder -t 'pipa-endeavouros-builder'
    - mkdir -p images
    - docker run --platform linux/arm64 --privileged -v "$(pwd)/images:/build/images" -v "/dev:/dev" pipa-endeavouros-builder plasma
    - docker run --platform linux/arm64 --privileged -v "$(pwd)/images:/build/images" -v "/dev:/dev" pipa-endeavouros-builder gnome
  artifacts:
    paths:
      - images/*.zip
    expire_in: 1 week

release_images:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build_images
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - export DATE=$(date +'%Y%m%d')
    - |
      release-cli create --name "EndeavourOS for Xiaomi Pad 6 (Pipa) $DATE" \
        --description "Automated build of EndeavourOS images for Xiaomi Pad 6 (Pipa)" \
        --tag-name "endeavouros-$DATE-$CI_COMMIT_SHORT_SHA" \
        --assets-link "{\"name\":\"Download ZIP Artifacts\",\"url\":\"$CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_REF_NAME/download?job=build_images\"}"
